version: "3.7"

volumes:
    app_volume:
        name: miner-volume
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":${PWD}"


services:
    miner:
        container_name: miner-raptoreum
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .data:/home
        privileged: true
